### PR TITLE
Specifications - Fix: Test for object property ranges

### PR DESCRIPTION
**Pull request by cmaumet**
Checking of object property ranges was ignored due to an indentation error. This pull request fix this issue and update the examples to correct for the error encountered after updating the test.

### CODE REVIEW

**Comment by nicholsn** [comment]
Happy to review once tests pass

**Comment by cmaumet** [comment]
Hi @nicholsn: tests are failing because of a timeout on the provstore but pass locally (cf #254). So I would say this is ready for review...

**Comment by nicholsn** [comment]
Thanks for the info, good to know.

**Comment by cmaumet** [comment]
Just rebased, tests now pass.

**Comment by nicholsn** [comment]
Great, thanks!

**Pull request merged**
