### PR TITLE
Definition of  "objectModel"

### PR DESCRIPTION
**Pull request by cmaumet**
**Terms**: `nidm:objectModel`, `nidm:NIDMObjectModel`, `nidm:FSLResults`, `nidm:SPMResults`
**Definition**: No definition yet...

This issue is open to discuss the definition of `objectModel` (attribute), `NIDMObjectModel` (range taken by `objectModel`) and `SPMResults` / `FSLResults` (sub-classes of `NIDMObjectModel`).

Example of use:
```
entity(niiri:spm_results_id,
    [prov:type = 'prov:Bundle',
    prov:label = "SPM Results",
    nidm:objectModel = 'nidm:SPMResults',
    nidm:version = "0.1.0"])
```

I am not sure about the naming of these terms. In particular, what is intended by "NIDM object models"? Are those the same as "NIDM components"? @satra I thought you might want to comment on this...

Any suggestion on the definitions or the naming is greatly appreciated.

### CODE REVIEW

**Comment by cmaumet** [comment]
(I have just re-implemented this PR to make it mergeable and include definitions). 

What do you think of these (adapted from @satra's suggestion):

 - **nidm:'NIDM Object Model'**: Abstraction on the data model, developed for a specific application/use-case/task at hand,  that specifies the components and relations necessary for use by these applications. The same object model can be reused by multiple applications (e.g., meta-analysis, Neurovault).
  - **nidm:'NIDM-Results'**: NIDM Object model representing the results of a mass univariate neuroimaging study and targeting the application of meta-analysis. The  specification is available at: http://nidm.nidash.org/specs/nidm-results.html

?

Example of usage:
```
niiri:spm_results_id a prov:Entity , prov:Bundle, nidm_NIDMResults: ;
	rdfs:label "NIDM-Results" ;
	nidm_version: "0.2.0"^^xsd:string .
```

**Comment by nicholsn** [comment]
+1

**Comment by cmaumet** [comment]
(rebased)

**Comment by cmaumet** [comment]
Thank you!

(Rebased on master).

@satra: I am going to merge this one but if you think this should be further discussed, please feel free to open a new issue.

**Comment by satra** [comment]
the new definitions look good.

**Comment by cmaumet** [comment]
Great! Thank you @satra. I have just made those terms "ready for release" (changes directly pushed on upstream after testing at cmaumet/nidm#26).

**Pull request merged**
