### PR TITLE
Re-use STATO terms in nidm Map definitions (e.g. ContrastMap)

### PR DESCRIPTION
**Pull request by cmaumet**
To make the best of the terms defined in STATO, how about updating our Map definitions to link to stato:

- **nidm:ContrastMap**: A map whose value at each element is a [`stato:"contrast estimate"`](http://purl.obolibrary.org/obo/STATO_0000384).
- **nidm:ParameterEstimateMap**: A map whose value at each element is a [`stato:"model parameter estimate"`](http://purl.obolibrary.org/obo/STATO_0000144).
- **nidm:StatisticMap**: A map whose value at each element is a [`stato:"statistic"`](http://purl.obolibrary.org/obo/STATO_0000039).

### CODE REVIEW

**Comment by cmaumet** [comment]
This is now implemented. @jbpoline: The residual mean squares map is in the nidm namespace. Is that what you were referring to?

**Comment by nicholst** [comment]
+1 for `nidm:ResidualMeanSquaresMap` as defined by @cmaumet

**Comment by cmaumet** [comment]
(Rebased on master).

**Comment by cmaumet** [comment]
Preview: Definition of [contrast map](http://htmlpreview.github.io/?https://raw.githubusercontent.com/cmaumet/nidm/map_definition_stato/doc/content/specs/nidm-results_dev.html#dfn-nidm-contrastmap), [parameter estimate map](http://htmlpreview.github.io/?https://raw.githubusercontent.com/cmaumet/nidm/map_definition_stato/doc/content/specs/nidm-results_dev.html#dfn-nidm-parameterestimatemap), [statistic map](http://htmlpreview.github.io/?https://raw.githubusercontent.com/cmaumet/nidm/map_definition_stato/doc/content/specs/nidm-results_dev.html#dfn-nidm-statisticmap), [residual mean squares map](http://htmlpreview.github.io/?https://raw.githubusercontent.com/cmaumet/nidm/map_definition_stato/doc/content/specs/nidm-results_dev.html#dfn-nidm-residualmeansquaresmap) and [contrast standard error map](http://htmlpreview.github.io/?https://raw.githubusercontent.com/cmaumet/nidm/map_definition_stato/doc/content/specs/nidm-results_dev.html#dfn-nidm-contraststandarderrormap) in the spec.

**Comment by cmaumet** [comment]
(Rebased on master). I think this is good to go: let's merge.

**Pull request merged**
