### PR TITLE
"Getting started with NIDM" page on the website

### PR DESCRIPTION
**Pull request by cmaumet**
In view of the upcoming OHBM, this PR update the nidm website to link to create a "Getting started with NIDM" page describing the NIDM-Results tools.

Screenshot:
image

Description of installation and usage of the SPM and FSL exporters are provided in their README, updated in https://github.com/incf-nidash/nidmresults-spm/pull/32 and https://github.com/incf-nidash/nidmresults-fsl/pull/92 respectively.

### CODE REVIEW

**Comment by nicholst** [comment]
++++1

**Comment by cmaumet** [comment]
Now online at: http://nidm.nidash.org/getting-started/.

**Comment by tiborauer** [comment]
Great work!
I wonder whether we want to advertise it on SPM and FSL mailing lists.

Vale,

Auer, Tibor M.D. Ph.D.
MRC Cognition and Brain Sciences Unit
15 Chaucer Road
Cambridge
CB2 7EF
United Kingdom
Phone/Work: +44-(0)1223-273613
Mail: Tibor.Auer@mrc-cbu.cam.ac.uk
________________________________

**Comment by cmaumet** [comment]
I really like this idea @tiborauer! I would say let's wait until @gllmflndn get the chance to look at the updated SPM exporter and provide us with some feedback and then we can advertise publicly on those mailing lists?

**Comment by nicholsn** [comment]
+1, very nice addition!

**Pull request merged**
