### PR TITLE
NIDM-Results matching with fMRI guidelines

### PR DESCRIPTION
**Pull request by cmaumet**
In an effort to represent the minimal metadata needed to describe an fMRI experiment as proposed in ["Guidelines for reporting an fMRI study" (Poldrack et. al 2008)](http://dx.doi.org/10.1016%2Fj.neuroimage.2007.11.048), I was wondering if we could add the following to NIDM-Results:
 - Type of model for first-level fMRI: block-based; event-related or mixed ;
 - A list of abstract names for the design matrix regressors.

The model could be updated as follows:
<pre>
niiri:design_matrix_id a prov:Entity , nidm:DesignMatrix ;
	rdfs:label "Design Matrix" ;
        ... other attributes ...
	<b>nidm:hasfMRIDesign nidm:eventRelatedDesign ;</b>
	<b>nidm:regressorNames {"reg1", "reg2", "reg3"} .</b>
</pre>

A complete mapping of the fMRI guidelines with NIDM-Results is available [here](
https://docs.google.com/spreadsheets/d/1iob7FHA43uGk5aQ8FdjlMweoY7Y2JZGez1QscuFewkk/edit?usp=sharing).

How would you feel about adding those two attributes to the design matrix?

### CODE REVIEW

**Comment by cmaumet** [comment]
This is now implemented (as initially proposed). If you are happy with this version, let me know and I will assign alphanumeric identifiers to the new terms before merging.

**Comment by cmaumet** [comment]
I forgot to include the proposed definitions in my last comment:

 - **nidm:hasfMRIDesign**: A property that associates an fMRI design to a design matrix in first-level fMRI analyses.
 - **nidm:fMRIDesign**: Type of fMRI design, one of block-based design event-related design or mixed design.
  - *nidm:BlockBasedDesign*: In a block-based design, all trials consists of epochs of sustained neural activity (blocks) (definition adapted from [MRC-CBU Design efficiency](http://imaging.mrc-cbu.cam.ac.uk/imaging/DesignEfficiency)).
  - *nidm:EventRelatedDesign*: In an event-related design, all trials consists of brief bursts of neural activity (impulses, or events) (definition adapted from [MRC-CBU Design efficiency](http://imaging.mrc-cbu.cam.ac.uk/imaging/DesignEfficiency))
  - *nidm:MixedDesign*: In a mixed design, a subset of the trials consists of epochs of sustained neural activity (blocks) and another subset consists of brief bursts of neural activity (impulses, or events) (definition adapted from [MRC-CBU Design efficiency](http://imaging.mrc-cbu.cam.ac.uk/imaging/DesignEfficiency))

 - **nidm:regressorNames**: A list of abstract names associated with each column of the design matrix (e.g. ["motor_left", "motor_right"]).

In the above, terms in *italics* are defined as individuals and terms in **bold** as classes.

**Comment by khelm** [comment]
Would it be more explicit to have the term be: nidm:fMRIDesignType?  Then the definition could be something like: "The type of stimulus presentation used in the data acquisition.", thereby trying to not use fMRI Design in the definition.

**Comment by nicholst** [comment]
+1 for `nidm:fMRIDesignType`

**Comment by tiborauer** [comment]
+1 for @khelm

**Comment by cmaumet** [comment]
+1 for @khelm's update (now implemented).

How do you feel about the rest of the definitions? If you are happy with them, please let me know and I will assign alphanumeric identifiers and merge.

**Comment by khelm** [comment]
+1 for the rest.

**Comment by nicholst** [comment]
Sorry @cmaumet, I didn't notice all the other definitions.

They are fine.  I struggle with the block design definition, but can't improve on it without writing a novel.

**Comment by khelm** [comment]
@nicholst , I did wonder about the focus in the definitions on the neural activity, e.g.,  a block is a period of sustained neural activity.  It would seem better to put more emphasis on the presented task being the same over the period, since you're only *hoping* that the neural activity is sustained.  Is that what your concern was?

**Comment by nicholst** [comment]
@khelm: What *I* struggled with was with a definition of "blocks" that used "trials"; some block designs do use of rapidly presented trials, but some blocks are really just a continuous stimulus (e.g. a rotating annular checkerboard, or an extended auditory stimulus).

But, now that you point it out, I *also* don't like the reference to neural activity (e.g. in the HRF definitions we use "anticipated neural responses"; #281).

So, starting from scratch, drawing inspiration from an [AFNI definition](http://afni.nimh.nih.gov/pub/dist/HOWTO/howto/ht03_stim/html/stim_background.html):

  - *nidm:BlockBasedDesign*: An fMRI design comprised of epochs of stimulus and/or behavior. 
  - *nidm:EventRelatedDesign*: An fMRI design comprised of discrete events of stimulus and/or behavior.  
  - *nidm:MixedDesign*: An fMRI design comprised of both epochs & discrete events of stimulus and/or behavior.

What do people think?  Since there is no universally agreed distinction on exactly what makes an event vs. an epoch, we leave it out of the definition.

If a reference/citation is essential, I would provide some review paper on the topic, like:  Amaro, E., & Barker, G. J. (2006). Study design in fMRI: Basic principles. Brain and Cognition, 60, 220–232.

**Comment by tiborauer** [comment]
It is quite close to my difinition apat from usinf "Design" instead of "Model" in the names, so +1.
However, according to @khelm's suggestion they could be "*DesignType".

**Comment by nicholst** [comment]
+1 for *`DesignType`

**Comment by cmaumet** [comment]
+1 for @nicholst's updated definitions (now implemented)

@tiborauer, @nicholst: we now do have *nidm:'fMRI Design Type'* (instead of *nidm:'fMRI Design'*), but I was not thinking we would add a suffix "type" to all the individual design-types: I would say that a "block-based design" is a design type (just like we use "t-statistic" as a "statistic type" and not "t-statistic type"). Does that make sense?

**Comment by cmaumet** [comment]
If you think this is ready to go, please merge (I will make sure to update all the remaining semantic ids just before the release).

**Comment by nicholst** [comment]
+1 to merge

**Comment by khelm** [comment]
+1 for @nicholst 's versions above.

**Comment by jbpoline** [comment]
I reviewed the definition - sound good to me as well. merging.

**Pull request merged**
