### PR TITLE
Re-use Neurolex/RRID SPM and FSL terms 

### PR DESCRIPTION
**Pull request by cmaumet**
Hi all,

I was thinking we could re-use the Neurolex terms [nlx:SPM](http://neurolex.org/wiki/Category:Resource:SPM) and [nlx:FSL](http://neurolex.org/wiki/Category:Resource:FSL) (which are also used in published papers as part of the [RRID](https://www.force11.org/Resource_identification_initiative) initiative) rather than creating our own `nidm:SPM` and `nidm:FSL` terms.

But... looking at the RDF export (e.g. [nlx:SPM RDF export](http://neurolex.org/wiki/Special:ExportRDF/:Category:Resource:SPM)), it looks like they are defined as OwlIndividuals, rather than Classes. (While in nidm we generate a different `nidm:SPM` (respectively `nidm:FSL`) individual for each document with its own software version as attribute.)

In terms of modelling, we could just use [nlx:SPM](http://neurolex.org/wiki/Category:Resource:SPM) and [nlx:FSL](http://neurolex.org/wiki/Category:Resource:FSL) as values for the prov:type attribute but I am not sure it's really a good practice to use an OwlIndividual as value of an rdf:type... Does someone have experience with this? Thoughts?

Thanks!

### CODE REVIEW

**Comment by cmaumet** [comment]
Re-use of [nlx:'SPM'](http://neurolex.org/wiki/nif-0000-00343) and [nlx:'FSL'](http://neurolex.org/wiki/birnlex_2067) is now implemented.

**Comment by tiborauer** [comment]
Do you mean this ontology: http://ontology.neuinfo.org/NIF/nif.owl
Should not it be abbreviated as "nif"?

**Comment by nicholsn** [comment]
The neurolex wiki also mints URIs: http://neurolex.org/wiki/Main_Page...
For example, the DICOM terms Karl has worked on:
http://neurolex.org/wiki/All_DICOM_terms

I believe the NIF ontology proper is mammalian anatomy.

**Comment by cmaumet** [comment]
On the [RRID website](http://scicrunch.com/resources), the "SPM" term points to http://neurolex.org/wiki/nif-0000-00343 and the "FSL" term to http://neurolex.org/wiki/birnlex_2067, so I thought "nlx" (for neurolex) would be appropriate but no strong feeling...

**Comment by tiborauer** [comment]
"SPM" points to "nif-0000-00343", which also uses "nif".

**Comment by cmaumet** [comment]
@tiborauer: "nif" indeed appears in the identifier of the SPM term but not in the namespace (which is "http://neurolex.org/wiki/"). In practice we would use nlx:nif-0000-00343 (for SPM) in the documents (and [nlx:SPM](http://neurolex.org/wiki/nif-0000-00343) for better readability in the spec). Does that make sense?

**Comment by tiborauer** [comment]
I guess we can choose any reference to a namespace. I was just wondering whether it was in concordance with any already existing practice...

**Comment by cmaumet** [comment]
(Rebased on master).

**Comment by cmaumet** [comment]
(Rebased on master)

**Comment by cmaumet** [comment]
(Rebased on master)

**Comment by cmaumet** [comment]
We discussed this on NIDASH call on March 30th ([Minutes](https://docs.google.com/document/d/1iPWwE2EvynkUrb9kTzmi9DQnE4WROeCYynYd0CpjwI8/edit?usp=sharing)) and agreed on the changes proposed in pull request.

**Comment by cmaumet** [comment]
(Rebased on master). I am going to merge this PR as agreed on NIDM call on March 30th  ([Minutes](https://docs.google.com/document/d/1iPWwE2EvynkUrb9kTzmi9DQnE4WROeCYynYd0CpjwI8/edit?usp=sharing)).

**Pull request merged**
