### PR TITLE
NIDM specifications: remove dependency on w3c website

### PR DESCRIPTION
**Pull request by cmaumet**
Recently, we (with @nicholst) experienced some delays when accessing the specifications at http://nidm.nidash.org/specs. It turned out that these resulted from difficulties in accessing the `respec-w3c-common` file on the w3c website `http://www.w3.org/Tools/respec/`. To avoid this issue in the future, this pull request updates the specifications so that they now rely on a "local" copy of `respec-w3c-common`.

### CODE REVIEW

**Comment by nicholst** [comment]
+1

**Comment by nicholsn** [comment]
​good idea, +1​

**Comment by khelm** [comment]
+1

**Comment by cmaumet** [comment]
Thank you!

**Pull request merged**
