### PR TITLE
Remove design type from NIDM-Results

### PR DESCRIPTION
**Pull request by cmaumet**
As discussed on [NIDM call (Nov. 16th, 2015)](https://docs.google.com/document/d/1VTqtJocBlly-_IhzBi8vfyg_f6LKcdSII2i0Jh6qoWU/edit?usp=sharing), this PR:
 - removes mention of `'design type'` from NIDM-Results (as this information cannot be reliably extracted automatically),
 - moves the related terms and definitions to NIDM-experiment.

### CODE REVIEW

**Comment by nicholst** [comment]
+1

**Comment by cmaumet** [comment]
(Rebase on master)

**Comment by nicholst** [comment]
I say go...

**Comment by tiborauer** [comment]
Do not we want to link it from NIDM-Exp? 
BTW, how about the other links? E.g. between NIDM-Exp's nidm:Condition and/or nidm:Task and NIDM-Res' nidm:'regressor Names'?

**Comment by cmaumet** [comment]
@tiborauer: 
 - Yes, the "design type" terms have been moved to NIDM-experiment. 
 - In NIDM-Results we limited our scope to metadata that can be automatically extracted. Unfortunately I don't think there is (yet) an automatic way to link regressor names with conditions/tasks... But as this becomes available, we will update NIDM-Results to make sure we link with NIDM-experiment.

**Comment by cmaumet** [comment]
This PR has been discussed on the call. I am going to merge this now.

**Pull request merged**
