### PR TITLE
Contributing working group

### PR DESCRIPTION
**Pull request by cmaumet**
This PR rewrites the README (based on https://github.com/acabunoc/mozsprint-repo-template/blob/master/README.md) to facilitate new contributions. 

@satra, @jbpoline, @samirdas: let me know what you think of this updated README (preview is [here](https://github.com/cmaumet/nidm/blob/master/README.md))!

(Next step is to create the CONTRIBUTING.md file.)

### CODE REVIEW

**Comment by satra** [comment]
Looks like a good start. 

Could we add a link to the google docs for the current workflow specification draft.

**Comment by cmaumet** [comment]
Thank you @satra! I've now added a link to the NIDM-Workflows spec: cf. [preview](https://github.com/cmaumet/nidm/blob/master/README.md).

**Comment by satra** [comment]
@cmaumet - thank you. LGTM. feel free to merge.

**Comment by cmaumet** [comment]
Thank you @satra!

**Pull request merged**
