### PR TITLE
New meta-analysis terms: number of subjects per group, modality, MRI protocol

### PR DESCRIPTION
**Pull request by cmaumet**
As discussed at the  [NIDM sprint (January 2016)](https://docs.google.com/document/d/1KU5doATDPmHHgNGgOot3rTdbjwi-MVY-v_tQkSZg868/edit?usp=sharing), this PR creates new terms that we identified as crucial for the meta-analysis use-case:
 - nidm:'number of Subjects Per Group' (attribute of nidm:'Data', [example](https://rawgit.com/incf-nidash/nidm/9e3ebbec9624b840f8aabaae34944cc095024380/doc/content/specs/nidm-results_dev.html#dfn-data))
 - nidm:'has MRI Protocol' (attribute of nidm:'Data', [example](https://rawgit.com/incf-nidash/nidm/9e3ebbec9624b840f8aabaae34944cc095024380/doc/content/specs/nidm-results_dev.html#dfn-data)) for MR datasets, to be chosen from Neurolex's: [functional MRI protocol](http://uri.neuinfo.org/nif/nifstd/birnlex_2177), [Diffusion-weighted imaging protocol](http://uri.neuinfo.org/nif/nifstd/nlx_inv_20090249), anatomical MRI protocol (under discussion).
 - nidm:'Data' is also linked to an Agent describing the imaging machine (using a `prov:wasAttributedTo` relation). The imaging machine must be chosen from Neurolex's: [MRI scanner](http://uri.neuinfo.org/nif/nifstd/birnlex_2100), PET scanner, SPECT scanner, EEG machine, MEG machine (under discussion at https://github.com/SciCrunch/NIF-Ontology/pull/34).

### CODE REVIEW

**Comment by chrisfilo** [comment]
Glad to see this coming together!

**Comment by cmaumet** [comment]
The proposition of new terms on Neurolex is open at: https://github.com/SciCrunch/NIF-Ontology/pull/34.

**Comment by nicholst** [comment]
+1

**Comment by proccaserra** [comment]
@cmaumet, STATO has the following:
study group population size
http://purl.obolibrary.org/obo/STATO_0000088
which seems suited for the need at hands. 

Hope this helps

**Comment by cmaumet** [comment]
Following discussions on re-use of Neurolex (https://github.com/SciCrunch/NIF-Ontology/pull/34, https://github.com/SciCrunch/NIF-Ontology/pull/41) and STATO (https://github.com/ISA-tools/stato/issues/38) terms, this PR was updated as follows:



 - The Group is defined as a stato:'study group population' and has the following attributes:
   - group Name
   - number Of Subjects
 - The Scanner is defined as a neurolex:'imaging instrument'.
 - The Data has the following new attribute:
  - nidm:'has MRI Protocol' that links to a neurolex:'MRI protocol' (functional/anatomical/structural)

This is now ready for final review and merge.

**Comment by cmaumet** [comment]
We discussed this PR on [NIDM call on March 21st](https://docs.google.com/document/d/1wcDUgkYEN4v9ruXI1vwLAwQlLfAdamLvC8VKwaWAsvo/edit?usp=sharing) and nobody objected.

**Comment by nicholsn** [comment]
does this need a revision on how to use the Reification Vocabulary?

**Comment by cmaumet** [comment]
@nicholsn: yes, that's right. But, I would say let's go with this version until we hear back from STATO. In the meantime, that will allow us to implement the update of the SPM and FSL exporters.

**Comment by nicholsn** [comment]
sounds good

**Pull request merged**
