### PR TITLE
Re-use STATO probability distribution terms for Error Distribution

### PR DESCRIPTION
**Pull request by cmaumet**
Following discussion at https://github.com/incf-nidash/nidm/pull/348#issuecomment-152537679 with @proccaserra and @nicholst, this PR implements the re-use of STATO `probability distribution` terms as a value for `nidm:'has Error Distribution'` object property used in the `nidm:'Error Model'` entity.

### CODE REVIEW

**Comment by cmaumet** [comment]
This is similar to what was done at #262 (to re-use STATO statistic terms), #252 (to re-use STATO estimation methods)...

**Comment by khelm** [comment]
I agree that we should re-use STATO terms as much as possible, but I just wish they were edited a bit better.  I've seen a number of instances like this:

"definition "A probability distribution is a information content entity specifies the probability of the value of a random variable."

It's not that it's wrong in content, but it's not grammatically correct.

**Comment by nicholst** [comment]
It is unfortunate. But my impression is that there is exactly one person (a tiny FTE) that works on it. Suggest an edit at https://github.com/ISA-tools/stato in my experience they (the one guy) is very responsive. 

-Tom

**Comment by proccaserra** [comment]
:) we will fix this as shortly and push it. We are in fact 2, Alejandra and myself, with input from Orlaith and of course you!
Another comment: it has to do with 'fMRI Design Type' and the notion of 'block based design'.
it seems to be related to the delivery of a treatment/stimulus (single exposure or repeated exposure).
I was wondering if the current term is meant to cover the declaration of 'blocking variable' and is related to 'randomized block design' ?

**Comment by cmaumet** [comment]
This was discussed on NIDM call on Nov 2nd and was agreed upon.

**Pull request merged**
