### PR TITLE
Exporter version

### PR DESCRIPTION
**Pull request by cmaumet**
As discussed on [NIDM call (Nov. 2nd 2015)](https://docs.google.com/document/d/1L6zioNC3qdmUb1pSU2iUHzV-Vpzy3J89j5c110kIroE/edit?usp=sharing), in this PR, we add the version of the exporter used to create a NIDM-Results document. To this aim, we: 
 - create a new attribute `nidm:'exporter Version'` in the Software Agent to store the version of the NIDM-Results exporter.
 - update the FSL examples to add the exporter version (in SPM, the exporter and the main software should have the same version number)

### CODE REVIEW

**Comment by gllmflndn** [comment]
> (in SPM, the exporter and the main software should have the same version number)

Would it be possible to keep them separate? The exporter would have a version number corresponding to the revision of spm_results_nidm.m - this would allow to have updates of the exporter that are not necessarily tied with those from the main software itself.

**Comment by cmaumet** [comment]
@gllmflndn: sure, this would be even better! If we need an exporter version for both SPM and FSL then we might want to create a separate entity (and activity) describing the NIDM-Results export... I will give it a try in this PR and we can discuss further.

**Comment by cmaumet** [comment]
(Rebased on master)

**Comment by cmaumet** [comment]
We discussed this on [NIDM call (November 23rd, 2015)](https://docs.google.com/document/d/1oOz6BeQ-g5v3lphlL39FqE2xkBTiGqiXRGIbCB-8tj8/edit?usp=sharing) and agreed to have another `SoftwareAgent` representing the exporter.

**Comment by cmaumet** [comment]
The exporter version is now encoded as discussed on [NIDM call (Nov. 23rd, 2015)](https://docs.google.com/document/d/1oOz6BeQ-g5v3lphlL39FqE2xkBTiGqiXRGIbCB-8tj8/edit?usp=sharing). In the process, the following terms have been created:

prov:Activity:
 - **nidm:'NIDM-Results Export' (nidm:NIDM_0000166)**: The process of exporting results created by a neuroimaging software (SPM, FSL, AFNI...) into a NIDM-Results archive.

prov:Agent
 - **nidm:'NIDM-Results Exporter' (nidm:NIDM_0000165)**: Tool used to export results produced by a neuroimaging software (SPM, FSL, AFNI...) into a NIDM-Results archive.
   - **nidm:'nidmfsl' (nidm:NIDM_0000167)**: Python library for the export of feat folders (generated by FSL) to NIDM-Results. Source available at: https://github.com/incf-nidash/nidm-results_fsl/.
   - **nidm:'spm_results_nidm' (nidm:NIDM_0000168)**: Matlab m file for the export of SPM results to NIDM-Results. Source available at: http://www.fil.ion.ucl.ac.uk/spm/download/toolbox/NIDM/spm_nidm.zip/.
 - **nidm:'Neuroimaging Analysis Software' (nidm:NIDM_0000164)**: Neuroimaging Analysis Software.

These definitions are marked as uncurated and are listed in the [terms to be reviewed](https://github.com/incf-nidash/nidm/tree/master/nidm/nidm-results/terms). I would suggest that we open separate issues to discuss the definitions.

**Comment by cmaumet** [comment]
Chart of the updated model:

**Comment by cmaumet** [comment]
This PR was agreed upon during the calls: let's merge!

**Pull request merged**
