### PR TITLE
Re-use STATO estimation methods

### PR DESCRIPTION
**Pull request by cmaumet**
Following ISA-tools/stato#32, "Ordinary Least Squares estimation", "Weighted Least Squares estimation", "Generalised Least Squares estimation", "Feasible Generalized Least Squares estimation" and "Iteratively Reweighted Least Squares estimation" are now defined in STATO.

This pull request implements the re-use of these terms as a value for `nidm:withEstimationMethod` object property used in the `nidm:ModelParametersEstimation` activity ([current implementation](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-modelparametersestimation), [proposed update preview](http://htmlpreview.github.io/?https://raw.githubusercontent.com/incf-nidash/nidm/8c2daba767b1cc6707677e80b4e4b1e6db5b46e8/doc/content/specs/nidm-results_dev.html#dfn-nidm-modelparametersestimation)).

### CODE REVIEW

**Comment by cmaumet** [comment]
Just rebased on master.

**Comment by nicholst** [comment]
+1

**Comment by cmaumet** [comment]
We discussed this issue on March 9th.

**Comment by jbpoline** [comment]
+1

**Comment by cmaumet** [comment]
Rebased on master. (Waiting for the test results to merge).

**Comment by jbpoline** [comment]
merging despinte the failed Travis - I believe this is the usual delay - let me know if this should be reverted.

**Comment by cmaumet** [comment]
Hi @jbpoline, thanks for the merge. The timeout issue is now solved so the tests should not fail anymore...  But you don't need to revert, I will just update the master branch manually to fix this small issue.

**Comment by cmaumet** [comment]
This is now fixed in master (last commit 641d469c1).

**Pull request merged**
