### PR TITLE
Noise FWHM in nidm namespace

### PR DESCRIPTION
**Pull request by cmaumet**
This is a proposal to move the "noiseFWHM" terms (i.e. `spm:'noise FWHM in units'`, `spm:'noise FWHM in voxels'` and `spm:'noise FWHM in vertices'`) to the nidm namespace.

We initially created those terms in the SPM namespace because those values were only reported for SPM results. But:
 - Since #301, we have considered that terms representing generic concepts would be defined in the nidm namespace. 
 - Moreover, issue #319 and #214 (cf. in particular https://github.com/incf-nidash/nidm/pull/214#issuecomment-6179982) have proposed to also report `'noise FWHM in units'` and `'noise FWHM in voxels'` for FSL (implemented in https://github.com/cmaumet/nidm-results_fsl/commit/82c51f9625bf10c31ed894ff373bf91d9fd714e0).

### CODE REVIEW

**Comment by nicholst** [comment]
+1

**Comment by khelm** [comment]
Do the terms have the same definition in SPM and FSL?

**Comment by cmaumet** [comment]
Yes, current definitions (for SPM) are generic and could also be used for FSL:
 - [spm:'noise FWHM In Voxels'](http://nidm.nidash.org/specs/nidm-results_100.html#dfn-spm_0000009): "Estimated Full Width at Half Maximum of the spatial smoothness of the noise process in voxels"
 - [spm:'noise FWHM In Units'](http://nidm.nidash.org/specs/nidm-results_100.html#dfn-spm_0000007): "Estimated Full Width at Half Maximum of the spatial smoothness of the noise process in world units"

**Comment by khelm** [comment]
OK, thanks.  +1

**Comment by nicholst** [comment]
For the record, FSL and SPM use different methods to estimate the FWHM (FSL uses correlation of residuals at pairs of adjacent voxels; SPM uses variance of the difference of residuals at pairs of adjacent voxels), but they are both trying to estimate the same intrinsic thing.

**Comment by khelm** [comment]
Ok, so in a sense they have different "definitions".  This seems to be a case where we should decide an overall strategy for this issue.  My view is that this is the kind of info that one would want to capture in the provenance, especially since we (i.e., you) actually know the difference.  So in the case where we could write a generic definition to cover all cases, but the underlying method is different, could we use the generic definition language, but then have a second sentence saying what method is used?

**Comment by cmaumet** [comment]
We discussed this on NIDASH call on May 11th.

**Comment by cmaumet** [comment]
(Rebased on master). I am going to merge this as agreed on NIDASH call on May 11th.

**Pull request merged**
