### PR TITLE
Reuse stato:'unstructured correlation structure'

### PR DESCRIPTION
**Pull request by cmaumet**
Following the introduction of stato:'unstructured correlation structure' in https://github.com/ISA-tools/stato/pull/42, this pull request:
 - deprecates nidm:'Arbitrarily Correlated Error' NIDM_0000003
 - import stato:'unstructured correlation structure' [STATO_0000405](http://purl.obolibrary.org/obo/STATO_0000405)

### CODE REVIEW

**Comment by cmaumet** [comment]
(Rebased on master)

**Comment by nicholst** [comment]
+1

**Comment by cmaumet** [comment]
(Rebased on master).

**Comment by cmaumet** [comment]
This is an extension of already agreed upon #306. I am going to merge now.

**Pull request merged**
