### PR TITLE
cleanup of sio, qibo, and nlx imports files and removal of extraneous…

### PR DESCRIPTION
**Pull request by khelm**
I've assigned imported terms to the correct branch of the graph, removed some unused terms and modified others to reflect the current usage as defined both by the Lucid Chart and by the work of @dbkeator in the BIDS-to-NIDM converter. The Role branch is now correct.

### CODE REVIEW

**Comment by khelm** [comment]
Can @cmaumet or someone familiar with the testing code take a look at the Travis error?  I have:
1) upgraded my version of nidmresults code
2) ran scripts/refresh.py
3) added the modified files, committed, and pushed the commit
4) run test/test_specifications.py   #run the Travis tests on my machine to make sure = ok
failed at first, then passed with warnings after ran:
 nidm/nidm-experiment/scripts/create_expe_specification.py
 nidm/nidm-results/scripts/create_results_specification.py

**Comment by cmaumet** [comment]
@khelm: sorry for the delay! On the tests run against your last commit (cf. [here](https://travis-ci.org/incf-nidash/nidm/builds/295892317?utm_source=github_status&utm_medium=notification)), it looks like there is an issue with `FSL_Software.txt` and `SPM_Software.txt`, have you tried rerunning manually: `nidm/nidm-results/scripts/create_term_examples.py`?  

```
======================================================================
ERROR: test_unit_examples (test_examples_match_templates.TestExamplesMatchTemplates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/incf-nidash/nidm/nidm/nidm-results/test/test_examples_match_templates.py", line 110, in test_unit_examples
    raise Exception(exception_msg)
Exception: 
FSL_Software.txt is not up to date with templates. Please use nidm/nidm-results/scripts/create_term_examples.py.
SPM_Software.txt is not up to date with templates. Please use nidm/nidm-results/scripts/create_term_examples.py.
```

**Comment by khelm** [comment]
I just ran nidm/nidm-results/scripts/create_term_examples.py but when I tried to push it back git reported that there were no changes. Is there a certain order that I should run it relative to the other pieces of code I mentioned above?

**Comment by cmaumet** [comment]
Hi @khelm! The order should not matter. I would like to look into this to try and debug what is going on. Hopefully I will have my new machine soon and will be able to send more feedback.

**Comment by khelm** [comment]
Hi @cmaumet - That would be great, thanks.

**Comment by cmaumet** [comment]
Hi again @khelm! I have managed to reproduce the problem on my machine. Can you try updating your install of the nidmresults package with:
```
pip uninstall nidmresults
pip install git+git://github.com/incf-nidash/nidmresults.git
```

and then rerunning:
```
python scripts/refresh.py
```
? This is what is done by travis (cf. [config file](https://github.com/incf-nidash/nidm/blob/master/.travis.yml)). A difference in version of the `nidmresults` package could explain the differences your are observing on your machine. I hope this will help.

**Comment by cmaumet** [comment]
That's great!

**Pull request merged**
