### PR TITLE
Search volume in voxels in nidm namespace

### PR DESCRIPTION
**Pull request by cmaumet**
In this pull request, discussed with @nicholst, we:
 - replace `spm:searchVolumeInVoxels` and `fsl:searchVolumeInVoxels` by a common term: `nidm:searchVolumeInVoxels`.

As the concept of *search volume measured in voxels* is the same across neuroimaging software, it seems that having a single term in the `nidm` namespace would be more appropriate (than having two separate terms for SPM and FSL).

### CODE REVIEW

**Comment by cmaumet** [comment]
(Rebased on master)

**Comment by nicholst** [comment]
+1 ... I'd say merge this puppy to support the rapid work needed on terms...

**Comment by tiborauer** [comment]
+1
Simplification is good! :D

**Comment by cmaumet** [comment]
Thank you and let's merge!

**Pull request merged**
